---
application:
  name: "social-server-facebookclone"
  project: "social-app-backend"
  organization: "QoveryCommunity"
routers:
- name: "main-social-server-facebookclone"
  routes:
  - application_name: "social-server-facebookclone"
    paths:
    - "/*"
